### PR TITLE
added erc20 factory example

### PR DESCRIPTION
**Pull request by dan13ram**

### CODE REVIEW

**Comment by pi0neerpat** [comment]
Nice, so this will be used for testing factory contracts?

Also is there an upgradeable example in here too?

**Comment by dan13ram** [comment]
I'm using the ERC20Upgradeable contract which has an init method instead of a constructor since I'm also using the eip 1167 way of cloning contracts instead of deploying new ones to save gas.

the subgraph is set up to use a template for the token and instantiate it every time the factory contract emits an event for a NewToken.

still needs documentation and updates to the deck

**Comment by dan13ram** [comment]
I think having the Upgradable in the token contract name may be confusing. Probably should change that, what do you think?

**Comment by pi0neerpat** [comment]
> using the eip 1167 way of cloning contracts instead of deploying new ones to save gas.

I think this is an excellent idea for the "factory" example here, since it's becoming industry standard

> I think having the Upgradable in the token contract name may be confusing

I think its ok

**Pull request merged**
